---
conf:
    box: "loic-roux-404/deb-g4"     # "bento/debian-10.2" (old | optional)
    private_ip: "192.168.56.111"    # VM IP in your host-only-network
    servername: ecoservice.com      # Servername and domain for your projects
    org: g4-dev                     # Organisation hosting repo
    projectname: ecs                # repo name with pattern src-{{projectname}}
    debug_playbook: false           # rsync to upload playbook (`vagrant rsync`)
    playbook_version: master        # master = stable | versions/beta
    testing_mode: 0                 # test services
    web_path: www                   # change web server if name != local_name
    app_env: dev                    # prod or dev
    ssl: false                      # Need re provision and manually adding cert to your machine settings
    nfs_force_disable: yes          # don't wan't nfs enabled because it's slow

smb: # prefer nfs on unix system
    enable: yes
    smb_user: ''
    smb_pass: ''

vm:
    name: ecoservice                # VM name for Virtualbox (string)
    memory: 2048                    # binary friendly value (int | 2048(min) / 3072 / 4096)
    cpus: 2                         # logical cores of vm (int | 2(min))
    cpuexecutioncap: 80             # virtual cpu, use high value with nfs (int | max: 100)
    natdnshostresolver1: "on"       # perf + (string | on/off)
    natdnsproxy1: "on"              # perf + (string | on/off)
    ioapic: "on"

rsync_exclude:
    - '/**/.DS_Store'
    - '*.lock'
    - '/**/node_modules/**'
    - '/**/vendor/**'
    - '.git'
    - '.vagrant'
    - '.idea/'
    - '.vscode/'
    - 'www/config/parameters.yaml'
    - 'www/phpunit.xml'
    - '/**/public/**/build/'
    - 'www/var/cache/**'
    - 'docs/**'
    - '.vscode/**'